### PR TITLE
Add support for LLVM 10

### LINKED ISSUE #59: [Feature Request] Add support for LLVM 10
Now that LLVM 10.0 has been released, it would be nice if CppAD CG supports it. As of now `LlvmModelLibrary` and `LlvmModelLibraryProcessor` are not created for LLVM 10.

### PR DESCRIPTION
**Pull request by acxz**
Resolves #59

### CODE REVIEW

**Comment by joaoleal** [comment]
Hello,

There are some additional changes still needed for clang 10.0 support.
We need to replace the following in [llvm_base_model_library_processor_impl.hpp](https://github.com/acxz/CppADCodeGen/blob/llvm-10/include/cppad/cg/model/llvm/v5_0/llvm_base_model_library_processor_impl.hpp):
```C++
        CompilerInvocation::setLangDefaults(*invocation->getLangOpts(), InputKind::C,
                                            llvm::Triple(invocation->TargetOpts->Triple),
                                            invocation->getPreprocessorOpts(),
                                            LangStandard::lang_unspecified);
```
with:
```C++
        CompilerInvocation::setLangDefaults(*invocation->getLangOpts(),
#if LLVM_VERSION_MAJOR >= 10
                                            InputKind(clang::Language::C),
#else
                                            InputKind::C,
#endif
                                            llvm::Triple(invocation->TargetOpts->Triple),
                                            invocation->getPreprocessorOpts(),
                                            LangStandard::lang_unspecified);
```
The following line needs to be added to llvm10_0.hpp:
```C++
#include  <clang/Basic/Builtins.h>
```
There is still another issue which I have been able to solve. I have some local changes which allow me to compile but I still don't know what are the differences with your PR.
I'm having issues during the linking step:

> [100%] Linking CXX executable llvm_link_clang
> /usr/bin/ld: /usr/lib/llvm-10/lib/libclangCodeGen.a(BackendUtil.cpp.o): na função "(anonymous namespace)::EmitAssemblyHelper::EmitAssemblyWithNewPassManager(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >)":
> (.text._ZN12_GLOBAL__N_118EmitAssemblyHelper30EmitAssemblyWithNewPassManagerEN5clang13BackendActionESt10unique_ptrIN4llvm17raw_pwrite_streamESt14default_deleteIS5_EE+0x1f15): referência não definida para "getPollyPluginInfo()"
> collect2: error: ld returned 1 exit status
> make[3]: *** [test/cppad/cg/model/llvm/CMakeFiles/llvm_link_clang.dir/build.make:108: test/cppad/cg/model/llvm/llvm_link_clang] Error 1
> make[2]: *** [CMakeFiles/Makefile2:3814: test/cppad/cg/model/llvm/CMakeFiles/llvm_link_clang.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:3821: test/cppad/cg/model/llvm/CMakeFiles/llvm_link_clang.dir/rule] Error 2
> make: *** [Makefile:1475: llvm_link_clang] Error 2

**Comment by joaoleal** [comment]
Another change is required. Replace in [llvm_base_model_library_processor_impl.hpp](https://github.com/acxz/CppADCodeGen/blob/llvm-10/include/cppad/cg/model/llvm/v5_0/llvm_base_model_library_processor_impl.hpp):
```C++
ArrayRef<const char*> args {"-Wall", "-x", "c", "string-input"}; // -Wall or -v flag is required to avoid an error inside createInvocationFromCommandLine()
```
with:
```C++
std::vector<const char*> args {"-Wall", "-x", "c", "string-input"}; // -Wall or -v flag is required to avoid an error inside createInvocationFromCommandLine()
```

**Comment by acxz** [comment]
Ah yeah I was able to figure out the `InputKind` issue, but yes still getting linking issues. I can go ahead and close this PR and let you take it up. Don't think I have knowledge the completely implement this.

**Comment by joaoleal** [comment]
I was able to get it to link and run successfully.
I'm attaching a patch with my changes if you would like to implement it in this PR:
[llvm-10.zip](https://github.com/joaoleal/CppADCodeGen/files/4914821/llvm-10.zip)

**Comment by acxz** [comment]
Sweet! Yeah I can put your patch on top of this PR. I'll give it a go later today.

**Comment by acxz** [comment]
@joaoleal sorry for taking some time, a couple busy days.

I had to convert your patch to a patch I could use with the `git apply` command (apparently idea patches dont work off the bat).

**Pull request merged**
