### PR TITLE
cmake: add uninstall command

### PR DESCRIPTION
**Pull request by jcarpent**
Following the same rules than in CppAD

### CODE REVIEW

**Comment by joaoleal** [comment]
CppADCodeGen uses a dual license (GPL3 or EPL1).
Is it possible to align the license of the file cmake/cppadcodegen_uninstall.cmake with these licenses?
It would be great if it could be GPL 2 or later and EPL 1 or later.

**Comment by joaoleal** [comment]
It appears the uninstall does not work if we install CppADCodeGen with 
```
make DESTDIR=someotherfolder install
```
Not sure how to fix it though.

**Comment by joaoleal** [comment]
Found the solution: https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/recipe/AddUninstallTarget

Just use `$ENV{DESTDIR}` before `${file}`.

**Comment by jcarpent** [comment]
> CppADCodeGen uses a dual license (GPL3 or EPL1).
> Is it possible to align the license of the file cmake/cppadcodegen_uninstall.cmake with these licenses?
> It would be great if it could be GPL 2 or later and EPL 1 or later.

Yes, sure. @ostasse, do you agree with the change in the license?

**Comment by jcarpent** [comment]
@joaoleal I'm done with the PR. Feel free to merge when you have time. Thanks for your feedbacks!

**Comment by joaoleal** [comment]
Please remove the `sudo: required` from .travis.yml (Travis stops using Docker images if it requires sudo).
We can test the install/uninstall with:
```
 - make DESTDIR=cppadcg-installation install
 - make DESTDIR=cppadcg-installation uninstall
```

**Comment by joaoleal** [comment]
I'll make the changes in develop before merging into master

**Comment by jcarpent** [comment]
@joaoleal Sorry for my late reply. Thanks for the changes.

**Pull request merged**
