### PR TITLE
[bugfix] Missed ; symbol

### PR DESCRIPTION
**Pull request by cmastalli**
Hi @joaoleal 

I would like to thank you for this great software.

I found a tiny bug in which this PR solves.

Best,
Carlos

### CODE REVIEW

**Comment by joaoleal** [comment]
Hello Carlos,

Thank you for the contribution.
I would not expect `CPPAD_ASSERT_UNKNOWN` to require a `;` since it is defined in [cppad_assert.hpp](https://github.com/coin-or/CppAD/blob/master/include/cppad/core/cppad_assert.hpp) as:
```C++
# ifdef NDEBUG
# define CPPAD_ASSERT_UNKNOWN(exp)      // do nothing
# else
# define CPPAD_ASSERT_UNKNOWN(exp)              \
{   if( ! ( exp ) )                         \
    CppAD::ErrorHandler::Call(              \
        false      ,                    \
        __LINE__   ,                    \
        __FILE__   ,                    \
        #exp       ,                    \
        ""         );                   \
}
# endif
```
If `NDEBUG` is defined, the macro is replaced with nothing (does not need the `;`).
If `NDEBUG` is not defined, the macro is replaced with:
```C++
 if( ! ( exp ) )
    CppAD::ErrorHandler::Call(
        false      ,
        __LINE__   ,
        __FILE__   ,
        #exp       , 
        ""         );
```
which also does not need the `;`.

Which version of CppAD and CppADCodeGen are you using?
With the version of CppADCodeGen from master and CppAD 20190200.4 the tests are compiling (see [Travis](https://travis-ci.org/joaoleal/CppADCodeGen/jobs/573097639)).
Perhaps there is something else.

**Comment by jcarpent** [comment]
The problem is that the function is not returning anything in the context where `NDEBUG` is defined.

**Comment by joaoleal** [comment]
I see what you mean.
Good catch.
Lets make it more explicit and use `break;` after the `CPPAD_ASSERT_UNKNOWN`.

**Comment by cmastalli** [comment]
@joaoleal - it's not yet clear for me if you want to remove `;` in `CPPAD_ASSER_UNKNOWN` lines, i.e.
```cpp
  CPPAD_ASSERT_UNKNOWN(0)
 break;
```

If so, I should also replicate this code style in all places, not only these two files. Using silver searcher you can see that there are places with `CPPAD_ASSER_UNKNOWN();`, i.e.
```bash
include/cppad/cg/atomic_fun_bridge.hpp
263:                    CPPAD_ASSERT_UNKNOWN(j < q);
325:        CPPAD_ASSERT_UNKNOWN(from.size() == to.size());
334:        CPPAD_ASSERT_UNKNOWN(from.size() == to.size());

include/cppad/cg/extra/sparse_forjac_hessian.hpp
279:        CPPAD_ASSERT_UNKNOWN(p_transpose.n_set() == n)
280:        CPPAD_ASSERT_UNKNOWN(p_transpose.end() == m)
288:            CPPAD_ASSERT_UNKNOWN(jac_row[sort_col[k]] < m && jac_col[sort_col[k]] < n)
289:            CPPAD_ASSERT_UNKNOWN(k == 0 || jac_col[sort_col[k - 1]] <= jac_col[sort_col[k]])
312:        CPPAD_ASSERT_UNKNOWN(hes_sparsity.n_set() == n)
313:        CPPAD_ASSERT_UNKNOWN(hes_sparsity.end() == n)
321:            CPPAD_ASSERT_UNKNOWN(hes_row[k] < n && hes_col[k] < n)
322:            CPPAD_ASSERT_UNKNOWN(k == 0 || hes_row[k - 1] <= hes_row[k])
430:                CPPAD_ASSERT_UNKNOWN(c <= j1)
564:    CPPAD_ASSERT_UNKNOWN(size_t(x.size()) == n)

include/cppad/cg/cond_exp_op.hpp
60:        CPPAD_ASSERT_UNKNOWN(0);
233:            CPPAD_ASSERT_UNKNOWN(0);

include/cppad/cg/lang/dot/language_dot.hpp
1404:            default: CPPAD_ASSERT_UNKNOWN(0);

include/cppad/cg/lang/c/language_c.hpp
2124:                CPPAD_ASSERT_UNKNOWN(0);

include/cppad/cg/lang/mathml/language_mathml.hpp
2077:                CPPAD_ASSERT_UNKNOWN(0);

include/cppad/cg/lang/latex/language_latex.hpp
2081:                CPPAD_ASSERT_UNKNOWN(0);
```

Let me know exactly what code style we adopt, and I propagate to all files if you agree with it.

**Comment by joaoleal** [comment]
Yes, let's just do the version:
'''c++
default:
  CPPAD_ASSERT_UNKNOWN(0)
  break;
'''
If 'CPPAD_ASSERT_UNKNOWN' is not in a switch, then there is no need to change.

**Comment by cmastalli** [comment]
I followed your suggestion + removed unnecessary `;` symbol in few other lines of code.

**Comment by joaoleal** [comment]
Merged.
Thank you for your contribution.

**Pull request merged**
